set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN T18 [get_ports U]
set_property IOSTANDARD LVCMOS33 [get_ports U]
set_property PACKAGE_PIN U17 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property PACKAGE_PIN T17 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property PACKAGE_PIN W19 [get_ports L]
set_property IOSTANDARD LVCMOS33 [get_ports L]
set_property PACKAGE_PIN U18 [get_ports C]
set_property IOSTANDARD LVCMOS33 [get_ports C]

set_property PACKAGE_PIN L1 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN P1 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property PACKAGE_PIN N3 [get_ports center]
set_property IOSTANDARD LVCMOS33 [get_ports center]
set_property PACKAGE_PIN P3 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property PACKAGE_PIN U3 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports down]

set_property PACKAGE_PIN A14 [get_ports clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out]